const restrictedGlobals = require("confusing-browser-globals");

module.exports = {
	root: true,
	parser: "@babel/eslint-parser",
	plugins: ["import"],
	env: {
		browser: true,
		es6: true,
		node: true,
	},
	parserOptions: {
		ecmaVersion: 2018,
		sourceType: "module",
		requireConfigFile: false,
	},
	extends: ["eslint:recommended"],
	settings: {
		"import/ignore": [
			"node_modules",
			"\\.(coffee|scss|css|less|hbs|svg|json)$",
		],
	},
	rules: {
		"array-callback-return": 1,
		"brace-style": 0,
		camelcase: 0,
		"comma-dangle": 0,
		"comma-style": 0,
		"consistent-return": 0,
		"default-case": [1, { commentPattern: "^no default$" }],
		"dot-location": [1, "property"],
		"dot-notation": 1,
		eqeqeq: 0,
		"getter-return": 1,
		indent: 0,
		"jsx-quotes": 0,
		"max-len": 0,
		"new-cap": [1, { capIsNew: false, newIsCap: true }],
		"new-parens": 1,
		"no-array-constructor": 1,
		"no-caller": 1,
		"no-cond-assign": [1, "except-parens"],
		"no-const-assign": 1,
		"no-control-regex": 1,
		"no-delete-var": 1,
		"no-dupe-args": 1,
		"no-dupe-class-members": 1,
		"no-dupe-keys": 1,
		"no-duplicate-case": 1,
		"no-empty-character-class": 1,
		"no-empty-pattern": 1,
		"no-duplicate-imports": 1,
		"no-else-return": 1,
		"no-empty": [1, { allowEmptyCatch: true }],
		"no-eval": 1,
		"no-ex-assign": 1,
		"no-extend-native": 1,
		"no-extra-bind": 1,
		"no-extra-label": 1,
		"no-extra-boolean-cast": 1,
		"no-extra-semi": 0,
		"no-fallthrough": 1,
		"no-func-assign": 1,
		"no-implied-eval": 1,
		"no-invalid-regexp": 1,
		"no-iterator": 1,
		"no-label-var": 1,
		"no-labels": [1, { allowLoop: true, allowSwitch: false }],
		"no-lone-blocks": 1,
		"no-loop-func": 1,
		"no-mixed-operators": [
			1,
			{
				groups: [
					["&", "|", "^", "~", "<<", ">>", ">>>"],
					["==", "!=", "===", "!==", ">", ">=", "<", "<="],
					["&&", "||"],
					["in", "instanceof"],
				],
				allowSamePrecedence: false,
			},
		],
		"no-mixed-spaces-and-tabs": 0,
		"no-multi-str": 1,
		"no-native-reassign": 1,
		"no-negated-in-lhs": 1,
		"no-new-func": 1,
		"no-new-object": 1,
		"no-new-symbol": 1,
		"no-new-wrappers": 1,
		"no-octal": 1,
		"no-octal-escape": 1,
		"no-redeclare": 1,
		"no-regex-spaces": 0,
		"no-restricted-globals": [2].concat(restrictedGlobals),
		"no-restricted-properties": 2,
		"no-restricted-syntax": [1, "WithStatement"],
		"no-script-url": 1,
		"no-self-assign": 1,
		"no-self-compare": 1,
		"no-sequences": 1,
		"no-shadow-restricted-names": 1,
		"no-sparse-arrays": 1,
		"no-template-curly-in-string": 1,
		"no-this-before-super": 1,
		"no-throw-literal": 1,
		"no-undef": 2,
		"no-unexpected-multiline": 0,
		"no-unreachable": 1,
		"no-unused-expressions": [
			1,
			{
				allowShortCircuit: true,
				allowTernary: true,
				allowTaggedTemplates: true,
			},
		],
		"no-unused-labels": 1,
		"no-unused-vars": [
			1,
			{
				args: "after-used",
				ignoreRestSiblings: true,
				varsIgnorePattern: "^(event|_)$",
			},
		],
		"no-useless-computed-key": 1,
		"no-useless-concat": 1,
		"no-useless-constructor": 1,
		"no-useless-escape": 1,
		"no-useless-rename": [
			1,
			{
				ignoreDestructuring: false,
				ignoreImport: false,
				ignoreExport: false,
			},
		],
		"no-use-before-define": [
			1,
			{
				functions: false,
				classes: false,
				variables: false,
			},
		],
		"no-var": 1,
		"no-with": 1,
		"no-whitespace-before-property": 1,
		"require-yield": 1,
		"rest-spread-spacing": [1, "never"],
		"one-var": 0,
		"operator-linebreak": 0,
		"prefer-const": 0,
		"quote-props": 0,
		quotes: 0,
		"require-await": 0,
		semi: 0,
		"space-before-blocks": 0,
		strict: [1, "never"], // assumed by babel
		"unicode-bom": [1, "never"],
		"use-isnan": 1,
		"valid-typeof": 1,
		"import/first": 2,
		"import/no-amd": 2,
		"import/no-anonymous-default-export": 1,
		"import/no-webpack-loader-syntax": 2,
	},
};
