module.exports = {
	extends: ["../index.js", "../jest/index.js"],
	parserOptions: {
		ecmaVersion: 2018,
		sourceType: "module",
		ecmaFeatures: {
			jsx: true,
		},
	},
	settings: {
		react: {
			version: "detect",
		},
	},
	plugins: [
		"react",
		"import",
		"jsx-a11y",
		"react-hooks",
		"jest",
		"testing-library",
	],
	env: {
		browser: true,
		commonjs: true,
		es6: true,
		jest: true,
		node: true,
	},
	rules: {
		"no-unused-vars": [
			1,
			{
				args: "after-used",
				ignoreRestSiblings: true,
				varsIgnorePattern: "^(event|_|React)$",
			},
		],
		"jsx-a11y/alt-text": 1,
		"jsx-a11y/anchor-has-content": 1,
		"jsx-a11y/href-no-hash": 0,
		"jsx-a11y/anchor-is-valid": [
			1,
			{
				aspects: ["noHref", "invalidHref"],
			},
		],
		"jsx-a11y/aria-activedescendant-has-tabindex": 1,
		"jsx-a11y/aria-props": 1,
		"jsx-a11y/aria-proptypes": 1,
		"jsx-a11y/aria-role": [1, { ignoreNonDOM: true }],
		"jsx-a11y/aria-unsupported-elements": 1,
		"jsx-a11y/heading-has-content": 1,
		"jsx-a11y/iframe-has-title": 1,
		"jsx-a11y/img-redundant-alt": 1,
		"jsx-a11y/no-access-key": 1,
		"jsx-a11y/no-distracting-elements": 1,
		"jsx-a11y/no-redundant-roles": 1,
		"jsx-a11y/role-has-required-aria-props": 1,
		"jsx-a11y/role-supports-aria-props": 1,
		"jsx-a11y/scope": 1,
		// https://github.com/yannickcr/eslint-plugin-react/tree/master/docs/rules
		"react/forbid-foreign-prop-types": [1, { allowInPropTypes: true }],
		"react/jsx-no-comment-textnodes": 1,
		"react/jsx-no-duplicate-props": 1,
		"react/jsx-no-target-blank": 1,
		"react/jsx-no-undef": 2,
		"react/jsx-pascal-case": [
			1,
			{
				allowAllCaps: true,
				ignore: [],
			},
		],
		"react/jsx-tag-spacing": 0,
		"react/jsx-uses-react": 1,
		"react/jsx-uses-vars": 1,
		"react/no-danger-with-children": 1,
		"react/no-deprecated": 0,
		"react/no-direct-mutation-state": 1,
		"react/no-is-mounted": 1,
		"react/no-typos": 1,
		"react/require-render-return": 2,
		"react/style-prop-object": 1,
		"react-hooks/rules-of-hooks": 1,
		"react-hooks/exhaustive-deps": 1,
	},
};
