module.exports = {
	extends: "../index.js",
	parserOptions: {
		ecmaVersion: 2019,
		ecmaFeatures: {
			jsx: true,
		},
		sourceType: "module",
	},
	plugins: ["react", "react-hooks", "jsx-a11y"],
	rules: {
		"jsx-a11y/accessible-emoji": 1,
		"jsx-a11y/alt-text": 1,
		"jsx-a11y/anchor-has-content": 1,
		"jsx-a11y/href-no-hash": 0,
		"jsx-a11y/anchor-is-valid": [
			1,
			{
				aspects: ["noHref", "invalidHref"],
			},
		],
		"jsx-a11y/aria-activedescendant-has-tabindex": 1,
		"jsx-a11y/aria-props": 1,
		"jsx-a11y/aria-proptypes": 1,
		"jsx-a11y/aria-role": 1,
		"jsx-a11y/aria-unsupported-elements": 1,
		"jsx-a11y/heading-has-content": 1,
		"jsx-a11y/iframe-has-title": 1,
		"jsx-a11y/img-redundant-alt": 1,
		"jsx-a11y/no-access-key": 1,
		"jsx-a11y/no-distracting-elements": 1,
		"jsx-a11y/no-redundant-roles": 1,
		"jsx-a11y/role-has-required-aria-props": 1,
		"jsx-a11y/role-supports-aria-props": 1,
		"jsx-a11y/scope": 1,
		// https://github.com/yannickcr/eslint-plugin-react/tree/master/docs/rules
		"react/forbid-foreign-prop-types": ["warn", { allowInPropTypes: true }],
		"react/jsx-no-duplicate-props": 2,
		"react/jsx-no-target-blank": 2,
		"react/jsx-no-undef": 2,
		"react/jsx-pascal-case": [
			1,
			{
				allowAllCaps: true,
				ignore: [],
			},
		],
		"react/jsx-tag-spacing": 0,
		"react/jsx-uses-react": 1,
		"react/jsx-uses-vars": 1,
		"react/no-danger-with-children": 1,
		"react/no-deprecated": 0,
		"react/no-did-mount-set-state": 1,
		"react/no-did-update-set-state": 1,
		"react/no-direct-mutation-state": 2,
		"react/no-is-mounted": 2,
		"react/no-string-refs": 2,
		"react/react-in-jsx-scope": 2,
		"react/require-render-return": 1,
		"react/style-prop-object": 1,
		"react-hooks/rules-of-hooks": 2,
		"react-hooks/exhaustive-deps": 1,
	},
};
