module.exports = {
  extends: '../index.js',
  plugins: ['wpcalypso'],
  env: {
    browser: true,
    commonjs: true,
    es6: true,
    jest: true,
    node: true,
    jquery: true,
  },
  rules: {
    'array-bracket-spacing': [1, 'always'],
    'comma-spacing': 1,
    'computed-property-spacing': [1, 'always'],
    curly: 1,
    'eol-last': 1,
    'func-call-spacing': 1,
    indent: [1, 'tab', { SwitchCase: 1 }],
    'key-spacing': 1,
    'keyword-spacing': 1,
    'no-multi-spaces': 0,
    'no-nested-ternary': 0,
    'no-spaced-func': 1,
    'no-trailing-spaces': 1,
    'no-underscore-dangle': 0,
    'object-curly-spacing': [1, 'always'],
    'padded-blocks': [1, 'never'],
    'semi-spacing': 1,
    'space-before-function-paren': [
      1,
      {
        anonymous: 'never',
        asyncArrow: 'always',
        named: 'never',
      },
    ],
    'space-in-parens': [1, 'always'],
    'space-infix-ops': [1, { int32Hint: false }],
    'space-unary-ops': [
      1,
      {
        overrides: {
          '!': true,
        },
      },
    ],
    'template-curly-spacing': [1, 'always'],
    'wpcalypso/i18n-ellipsis': 2,
    'wpcalypso/i18n-no-collapsible-whitespace': 1,
    'wpcalypso/i18n-no-variables': 1,
    'wpcalypso/i18n-no-placeholders-only': 1,
    'wpcalypso/i18n-no-this-translate': 1,
    'wpcalypso/i18n-mismatched-placeholders': 2,
    'wpcalypso/i18n-named-placeholders': 2,
    'wpcalypso/import-docblock': 0,
    'wpcalypso/jsx-gridicon-size': 1,
    'wpcalypso/jsx-classname-namespace': 1,
    'wpcalypso/redux-no-bound-selectors': 1,
    yoda: 0,
  },
};
